### PR TITLE
Fix ProtobufBundle.MinVersion

### LINKED ISSUE #227: MinVersion not compatible with Bundle v0.3
**Description**

`ProtobufBundle.MinVersion` is not compatible with the new v0.3 Bundle MediaType which ends with `+json`.

This is used by the flag `-minBundleVersion` flag in the CLI.

### PR DESCRIPTION
**Pull request by codysoyland**
Fixes #227

Signed-off-by: Cody Soyland <codysoyland@github.com>

### CODE REVIEW

File: pkg/bundle/bundle_test.go [hunk 1]
```diff
@@ -106,6 +106,39 @@ func Test_getBundleVersion(t *testing.T) {
...
+	t.Parallel()
+	for _, tc := range []struct {
+		name            string
+		mediaType       string
+		expectedVersion string
+		ret             bool
+	}{
+		{"old-format", "application/vnd.dev.sigstore.bundle+json;version=0.1", "v0.1", true},
+		{"old-format-unexpected", "application/vnd.dev.sigstore.bundle+json;version=0.1", "v0.2", false},
+		{"old-format-without-v", "application/vnd.dev.sigstore.bundle+json;version=0.1", "0.1", true},
```
Comment (Hayden-IO) [inline pkg/bundle/bundle_test.go:119]: Do we want to support matching both with and without the preceding `v`, or should we standardize around one?

Comment (kommendorkapten) [reply pkg/bundle/bundle_test.go:119]: I would favour the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) here, i.e what's implemented. 
As this is a simple helper function, requiring stricter formatting does not seem to aid in any correctness IMHO.

edit: grammer fix.

**Review by kommendorkapten — APPROVED** [review]
🚀
