### PR TITLE
Fix intoto unmarshal

### LINKED ISSUE #365: JSON marshal of VerificationResult yields incorrectly-formatted in-toto attestation
**Description**

Due to in-toto moving to protobuf, there is an issue where marshalling `VerificationResult` (with `json.Marshal`) will produce a JSON object with an incorrectly formatted in-toto statement.

Specifically, the `predicateType` field is named `predicate_type`, and other fields are made into snake_case instead of the expected `camelCase` as [required by spec.](https://github.com/in-toto/attestation/blob/main/spec/v1/predicate.md)

### PR DESCRIPTION
**Pull request by codysoyland**
#### Summary

This PR is a modified copy of @gillisandrew's https://github.com/sigstore/sigstore-go/pull/326 with some slight simplifications. It is API-compatible with the existing codebase.

The [attempt to upstream](https://github.com/in-toto/attestation/pull/403) the fix for this is taking longer than expected, so this fix will serve as a temporary solution.

Fixes #365

### CODE REVIEW

File: pkg/verify/signed_entity_test.go [hunk 1]
```diff
@@ -422,3 +424,47 @@ func TestSigstoreBundle2Sig(t *testing.T) {
...
+
+	result := verify.NewVerificationResult()
+	result.Statement = &statement
+
+	// marshal the statement to JSON
+	statementJSON, err := json.Marshal(result)
+	assert.NoError(t, err)
+	want := `
+	{
+		"mediaType": "application/vnd.dev.sigstore.verificationresult+json;version=0.1",
```
Comment (phillmv) [inline pkg/verify/signed_entity_test.go:452]: This is technically not `verificationResult`'s fault at all but since we _are_ modifying the schema as a result of this change, I feel like it'd be reasonable to increment the version 🤔.

File: pkg/verify/signed_entity.go [hunk 2]
```diff
@@ -221,6 +223,26 @@ func NewVerificationResult() *VerificationResult {
 	}
 }
 
+// MarshalJSON deals with protojson needed for the Statement.
+// Can be removed when https://github.com/in-toto/attestation/pull/403 is merged.
+// TODO: Should we also add UnmarshalJSON?
```
Comment (phillmv) [inline pkg/verify/signed_entity.go]: If someone were to try to parse the json ouput using Go,

- would they use this library's types to do so?
- would the unmarshal step work with the output sans errors?

if it would error out otherwise, seems wise to provide a working output/input loop by default (i.e. yes to adding an UnmarshalJSON)?

File: pkg/verify/signed_entity_test.go (hunk 1 above)
Comment (codysoyland) [reply pkg/verify/signed_entity_test.go:452]: I don't really care either way, but this is a recently-introduced bug, and older versions of sigstore-go produced the correct schema and called it `0.1`. But we can call it whatever because I am unaware of anything that actually parses this mediatype.

File: pkg/verify/signed_entity.go (hunk 2 above)
Comment (codysoyland) [reply pkg/verify/signed_entity.go]: I'm just being lazy. It's easy enough to add, so I'll do it.

File: pkg/verify/signed_entity_test.go (hunk 1 above)
Comment (Hayden-IO) [reply pkg/verify/signed_entity_test.go:452]: Given it's a bug fix, keeping it the same seems reasonable.

**Review by Hayden-IO — APPROVED** [review]
Creative solution with the alias!
