### PR TITLE
Don't fail on Rekor entry verification for untrusted entries

### LINKED ISSUE #43: Timestamp verification should not fail unless the threshold is not met
**Description**

Looking at https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/tsa.go#L64, if any timestamp verification fails, then the verifier errors out. Instead, the verifier should succeed as long as the threshold for successful timestamp signatures is met. If there's N timestamps, and the threshold is 1, then the verifier only needs 1 timestamp to verify to succeed.

### PR DESCRIPTION
**Pull request by Hayden-IO**
Like #45, as long as the threshold of expected timestamps is met, then verification should succeed. Otherwise, entries without trust root material should be skipped.

One benefit of having the log key ID be used to look up the correct trust root material is that we can still error out if the signature is invalid.

Fixes #43

### CODE REVIEW

File: pkg/verify/sct.go [hunk 1]
```diff
@@ -48,7 +49,8 @@ func VerifySignedCertificateTimestamp(leafCert *x509.Certificate, threshold int,
 		encodedKeyID := hex.EncodeToString(sct.LogID.KeyID[:])
 		key, ok := ctlogs[encodedKeyID]
 		if !ok {
-			return fmt.Errorf("unable to find ctlogs key for %s", encodedKeyID)
+			// skip entries the trust root cannot verify
```
Comment (steiza) [inline pkg/verify/sct.go:52]: This is definitely the behavior we want, but we are losing a lot of valuable feedback from the library as it verifies the bundle, which has been very helpful in debugging!

I wonder if we should add a debug mode to sigstore-go, where it still prints these messages out, but continues / doesn't error out.

File: pkg/verify/tlog.go [hunk 2]
```diff
@@ -78,14 +75,14 @@ func VerifyArtifactTransparencyLog(entity SignedEntity, trustedMaterial root.Tru
 		if err != nil {
 			return nil, err
 		}
+		inclusionVerified := false
```
Comment (steiza) [inline pkg/verify/tlog.go]: Minor: the reason this was scoped to `!online` before was because we want to ensure there was at least one of an inclusion promise or an inclusion proof (e.g. you couldn't cheat by having neither, and falling through to have your timestamp be listed as verified).

I think with the `continue` statements, and with the placement of `if inclusionVerified` inside the `for` loop, we don't actually need it for the `online` case? But also, it's not hurting anything.

File: pkg/verify/tlog_test.go [hunk 3]
```diff
@@ -52,6 +52,47 @@ func TestTlogVerifier(t *testing.T) {
 	assert.Error(t, err)
 }
 
+type goodAndUntrustedLogEntry struct {
```
Comment (steiza) [inline pkg/verify/tlog_test.go]: Minor: I updated the wording on https://github.com/sigstore/sigstore-go/pull/45/files that you could consider adopting here: `oneTrustedOneUntrustedTimestampEntity`, `UntrustedTestEntity`, etc.

**Review by steiza — COMMENTED** [review]
Generally looks good to me! Looking for other folk's opinion about debug statements / a debug mode.

File: pkg/verify/sct.go (hunk 1 above)
Comment (kommendorkapten) [reply pkg/verify/sct.go:52]: Something like an addition to the `VerificationResult`, were ignored entries are stored? Could of course be a separate struct too. Then a client may opt to offer a debug or verbose mode where such information is shown?

**Comment by kommendorkapten** [comment]
Looks good, and I agree with @steiza that we may want to have some option to get details on ignored signatures. I'm fine to merge this then track that as a separate issue as it would be a larger refactor (to cover TSAs too).

**Review by kommendorkapten — DISMISSED** [review]

File: pkg/verify/tlog_test.go (hunk 3 above)
Comment (Hayden-IO) [reply pkg/verify/tlog_test.go]: done

File: pkg/verify/sct.go (hunk 1 above)
Comment (Hayden-IO) [reply pkg/verify/sct.go:52]: Good suggestion! Tracking in https://github.com/sigstore/sigstore-go/issues/48 if that's alright.

File: pkg/verify/tlog.go (hunk 2 above)
Comment (Hayden-IO) [reply pkg/verify/tlog.go]: Yep, I think this looks cleaner without. Lemme know if I misunderstood something and removed too much.

Comment (Hayden-IO) [reply pkg/verify/tlog.go]: I miss `goto` statements. I genuinely think they're cleaner than `continue`....

File: pkg/verify/tlog.go [hunk 4]
```diff
@@ -106,19 +103,15 @@ func VerifyArtifactTransparencyLog(entity SignedEntity, trustedMaterial root.Tru
...
 					return nil, err
 				}
-
-				inclusionVerified = true
-			}
-
-			if inclusionVerified {
-				verifiedTimestamps = append(verifiedTimestamps, entry.IntegratedTime())
 			}
+			verifiedTimestamps = append(verifiedTimestamps, entry.IntegratedTime())
```
Comment (steiza) [inline pkg/verify/tlog.go:109]: Ah, so we don't want to append to `verifiedTimestamps` in the `if !entry.HasInclusionPromise() && !entity.HasInclusionProof()` case; we want to make sure at least one of these is true, so I think we still need `inclusionVerified` around this part.

Comment (Hayden-IO) [reply pkg/verify/tlog.go:109]: @steiza Good catch! Instead of adding `inclusionVerified` back, I fixed the TODO to check that one of these is true, since it would be an invalid entry if neither was.

I added two tests to catch this, one that creates an invalid entry without a proof or promise and one without any entries.

**Comment by Hayden-IO** [comment]
@steiza Just a post-holiday bump to review! The change is also in https://github.com/sigstore/sigstore-go/pull/51

**Review by steiza — APPROVED** [review]
Nice work! The test to ensure we don't "fall through" and verify if there's no inclusion proof and no inclusion promise is great.
